main: ImportMap\Main
api: 3.1.1
load: POSTWORLD

name: ImportMap
description: Import Maps
version: 2.2-<PMIMPORTER>
author: aliuly

commands:
    im:
        description: Import Map
        usage: "/im <path> <world>"

permissions:
    im.cmd.im:
        default: op
        description: "Allows users to import maps"
